language: php

php:
  - 7.2 

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction

before_script:
  - cp phpunit.xml.dist phpunit.xml

script:
  - phpunit
  - ./vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src

notifications:
  email:
    on_success: never
    on_failure: change
